db:
  user: 'threed'
  pw: 'Sep46694%'
  host: 'mysql.clarksonmsda.org'
  db: 'threed_cliff_jump_registry'
poll_user: 'threed'
mapbox:
  token: 'pk.eyJ1IjoidHJyMmtlIiwiYSI6ImNtaWVrd3doNzA0NDczY3BzZGY0Y2JjMWMifQ.XanllrA8yHIowp-J-wfYkg'
tables:
  user: 'Users'
  JumpLogs: 'JumpLogs'
  Locations: 'Locations'
  LocationVerificaitons: 'LocationVerificaitons'
  Reviews: 'Reviews'
  SafetyReports: 'SafetyReports'

